In [1]:
import numpy as np
import matplotlib.pyplot as plt
from scipy import optimize

## Tutorial
https://docs.scipy.org/doc/scipy/reference/tutorial/optimize.html#constrained-minimization-of-multivariate-scalar-functions-minimize

In [2]:
X = np.array([1,2,3])
y = np.array([20,10,50])
def ln_reg(param):
    global X, y
    a, b = param
    y_pred = a*X + b
    diff = y_pred - y
    return sum(abs(diff))

param0 = np.array([1,1])
res = optimize.minimize(ln_reg, param0, method='nelder-mead',
                       options={'xatol': 1e-8, 'disp': True})
res.x

Optimization terminated successfully.
         Current function value: 25.000000
         Iterations: 109
         Function evaluations: 206


array([15.        ,  4.99999999])

In [3]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression().fit(X.reshape(-1,1),y)
reg.coef_

array([15.])

In [4]:
def standard_constraint(param):
    a1, a2, standard = param
    return a1 - standard*a2

In [50]:
#Without using class:
def chlorophyll_function(phosphate_rate, nitrate_rate, phosphate, nitrate):
    """
    Function that model the chlorophyll
    """
    return phosphate_rate*phosphate + nitrate_rate*nitrate

def objective_function(rate_parameters):
    """
    Function of the difference between the 
    predicted chlorophyll (from the chlorophyll_function)
    and the actual chlorophyll
    """
    global train_phosphate, train_nitrate, train_chlorophyll
    phosphate_rate, nitrate_rate = rate_parameters
    predicted_chlorophyll = chlorophyll_function(phosphate_rate, nitrate_rate, 
                                                 train_phosphate, train_nitrate)
    difference = train_chlorophyll - predicted_chlorophyll
    return np.sum(difference**2)

def constraint_1():
    """
    Constraint that all the components of the parameter array are positive. 
    """
    lower_bound = [0,0] #Greater than 0
    upper_bound = [np.inf, np.inf]
    T_matrix = [[1,0],[0,1]] #Transfer the parameter array to corresponding components
    return optimize.LinearConstraint(T_matrix, lower_bound, upper_bound)

def func_of_constraint_2():
    """
    rate P/ rate N - N_over_P_standard
    PRESUME N_over_P_standard = 10
    
    """
    return lambda x: x[0] - x[1]*10

def constraint_2():
    function = lambda x: x[0] - x[1]*10
    deviation = 10**(-3)
    return optimize.NonlinearConstraint(function, 0-deviation, 0+deviation)
    
def model_result(train_phosphate, train_nitrate, train_chlorophyll):
    """
    Minimize the objective function to get the optimized 
    phosphate_rate and nitrate_rate
    """
    model = optimize.minimize(objective_function, np.array([0,0]),
                              constraints=[constraint_1(), constraint_2()])
    return model.x

def predict(X):
    """
    Predict the chlorophyll from the given phosphate and nitrate 
    """
    return 0

In [51]:
train_phosphate = np.array([1,2,3,4])
train_nitrate = np.array([1,3,2,5])
train_chlorophyll = np.array([1,5,3,7])
model_result(train_phosphate, train_nitrate, train_chlorophyll)

array([1.45164395, 0.1452644 ])

In [21]:
model = NutrientModel()
phosphate = np.array([1,2,3,4])
nitrate = np.array([1,3,2,5])
chlorophyll = np.array([1,5,3,7])
model.fit(phosphate,nitrate,chlorophyll)

In [9]:
model.phosphate_rate

-0.11111110008150264